### ISSUE TITLE
Consider moving to swaywm GitHub org

### ISSUE THREAD

**Issue by SirCmpwn** [way-cooler/wlroots-rs#2]
I've established the [swaywm GitHub org](https://github.com/swaywm) and moved wlroots there. We have discussed maintaining wlroots API wrappers within the swaywm organization - if you'd like, I can add you and we can host it there. Of course, the project would remain yours and you'd still have complete autonomy over it.

**Comment by Timidger** [comment]
Sounds good. I was planning on starting this back up again soon (I'll probably take a look this weekend actually). Feel free to add me whenever, and I'll transfer/clone this repo over when you do.

**Comment by SirCmpwn** [comment]
Thanks!

**Comment by acrisci** [comment]
I don't know rust, but I'm interested in learning. I know wlroots pretty well, so if you make issues, I'll contribute to development of wlroots-rs.

**Comment by Timidger** [comment]
@acrisci Good to hear, I know you've been active in the wlroots work.

Most of the work will be making safe wrappers around the wlroots types (eg safe in terms of memory safety, since Rust strives to be memory safe). This will mean trying to make functions that, while implemented using "unsafe" Rust code will be safe from the library user's perspective (eg, they can't accidentally get a dangling pointer).

When I restart work on this (probably this weekend is when I'll have time) I'll be sure to make issues.
